### ISSUE TITLE
Ao chamar o metódo Endpoints ocorre uma exceção

### ISSUE THREAD

**Issue by daniel-scatigno** [gerencianet/gn-api-sdk-dotnet-core#1]
Ao chamar o metódo Endpoints ocorre uma exceção de diretório.

Could not find a part of the path '/home/discos/coisas/Projeto Quem me Atende/quemmeatende.netcore/Gerencianet.SDK/endpoints.json'."

Na linha 23 do arquivo Endpoints.cs
endpoints = JObject.Parse (File.ReadAllText ("../Gerencianet.SDK/endpoints.json"));
O diretorio não existe, pois a chamada dessa forma leva para o Root da aplicação e não para o Binário. O Problema é que o arquivo endpoints.json é copiado para o mesmo diretório onde esta o binário da aplicação

**Comment by pallomabritoGN** [comment]
Problema corrigido na release 2.0.1.
