### ISSUE TITLE
Endpoints certificate

### ISSUE THREAD

**Issue by daniel-scatigno** [gerencianet/gn-api-sdk-dotnet-core#6]
Olá, na nova versão foi adicionado o atributo certificate no método Endpoints
![image](https://user-images.githubusercontent.com/1984798/176329429-53b6be0b-dfc3-4ba3-8183-47492cfab65e.png)

O que é este atributo? 

Não achei em nenhuma documentação falando sobre o que é este atributo.

O único lugar que achei uma mensão foi em:
![image](https://user-images.githubusercontent.com/1984798/176329554-c3eb2b7c-9d59-490e-9f3b-12e32b8a2335.png)

**Comment by pallomabritoGN** [comment]
Olá Daniel! Tudo bem?
Todas as requisições utilizando a API Pix devem conter um certificado de segurança que é fornecido pela Gerencianet dentro da sua conta, no formato PFX(.p12). Essa exigência está descrita na íntegra no [manual de segurança do PIX](https://www.bcb.gov.br/estabilidadefinanceira/comunicacaodados).
Disponibilizamos mais detalhes em nossa [documentação](https://dev.gerencianet.com.br/docs/api-pix-autenticacao-e-seguranca#section-gerando-um-certificado-p12).

**Comment by danielscatigno-ncpc** [comment]
Ok @pallomabritoGN , obrigado, vou atualizar minha aplicação
